### ISSUE TITLE
Use Async Web Server with Nucleo-H743 or H745

### ISSUE THREAD

**Issue by malbrook** [khoih-prog/AsyncWebServer_STM32#3]
Whwn compiling the examples for use with the Nucleo-H743ZI2 board I get errors due to missing definitions, where do I find definitions of items such as ETH_RXBUFNB, ETH_TXBUFNB as I need to define these for this Nucleo board which is supported by the Arduino compiler but not by this library.

regards M Brook

**Comment by khoih-prog** [comment]
The library can support only STM32 boards with **built-in LAN8742A Ethernet.**

Check [**Currently Supported Boards**](https://github.com/khoih-prog/AsyncWebServer_STM32#currently-supported-boards)

> 
>    Currently support
>    STM32 boards with built-in Ethernet (to use USE_BUILTIN_ETHERNET = true) such as :
>       - Nucleo-144 (F429ZI, F767ZI)
>       - Discovery (STM32F746G-DISCOVERY)
>       - STM32 boards (STM32F/L/H/G/WB/MP1) with 32K+ Flash, with Built-in Ethernet,
>       - See How To Use Built-in Ethernet at (https://github.com/khoih-prog/EthernetWebServer_STM32/issues/1)

Whenever the board has built-in **LAN8742A** Ethernet, those definitions will be auto-included in the board package.

If you decide to add **LAN8742A** Ethernet into your board (certainly with correct hardware design), you have to modify the board package (a little more complicated job, but just imitate what have been done with Nucleo-144 **F767ZI, F429ZI**, etc.)

**Comment by malbrook** [comment]
Hi
but the Nucleo-F743ZI2, Nucleo-H743ZI and the Nucleo-H745 all have the LAN8742A fitted, see the attached diagram from ST Microelectronics, but none of them will compile. Thety give errors regarding definition of a number of ETH_.... defines
[en.MB1364-H743ZI-C01_Schematic.pdf](https://github.com/khoih-prog/AsyncWebServer_STM32/files/5907242/en.MB1364-H743ZI-C01_Schematic.pdf)

**Comment by khoih-prog** [comment]
This library relies on [**STM32Ethernet Library**](https://github.com/stm32duino/STM32Ethernet), which in turn relies on the [**STM32 core**](https://github.com/stm32duino/Arduino_Core_STM32) to support F767ZI, F756ZG, F429ZI, F746ZG

Currently, the [**STM32 core**](https://github.com/stm32duino/Arduino_Core_STM32) doesn't support H743ZI, H743ZI2, H745 using [**STM32Ethernet Library**](https://github.com/stm32duino/STM32Ethernet). You can try by test compile a simple Ethernet example,such as [**WebClient**](https://github.com/stm32duino/STM32Ethernet/tree/master/examples/WebClient).

I certainly can modify the core to provide Ethernet support, but I have no such H7 board as well as time to do / test. So, you can do that or post on the [**Arduino_Core_STM32 isue**](https://github.com/stm32duino/Arduino_Core_STM32/issues) to request an enhancement.

**Currently the Ethernet is not supported on H7.**

1. [**mqtt_STM32Ethernet.ino doesn't compile with Nucleo H743ZI2 #28**](https://github.com/stm32duino/STM32Examples/issues/28)
2. [**Open Support Nucleo-H743 #21**](https://github.com/stm32duino/STM32Ethernet/issues/21)

Many people are experiencing the Ethernet issue with H7 boards. Have a look at to see if you can use the solution

1. [Ethernet not working on STM32H7x3](https://community.st.com/s/article/FAQ-Ethernet-not-working-on-STM32H7x3)
2. [NUCLEO-H743ZI2 lwIP TCP Connection](https://stackoverflow.com/questions/59863930/nucleo-h743zi2-lwip-tcp-connection)
3.  [Why STM32Cube_FW_H7_V1.2.0 ethernet sample code not run in nucleo-h743zi board](https://community.st.com/s/question/0D50X00009XkWuy/why-stm32cubefwh7v120-ethernet-sample-code-not-run-in-nucleoh743zi-board)

I suggest you, if in a rush, use the F767ZI which is currently supported by the core as well as those above-mentioned libraries.

Good Luck,
