### ISSUE TITLE
Async_AdvancedWebServer_LAN8720

### ISSUE THREAD

**Issue by pxvga** [khoih-prog/AsyncWebServer_STM32#9]
when compiling this example for the Black F407VG board using Arduino Core for STM32 v2.3.0, there are errors; when using v2.2.0 everything is fine. Am I missing something?

**Comment by khoih-prog** [comment]
Check [**Important Change from v1.5.0**](https://github.com/khoih-prog/AsyncWebServer_STM32#important-change-from-v150)

This is the issue caused by the **breaking STM32 core v2.3.0+,** but I'm dropping the support of LAN8720 + new STM2 cores as I'm not interested in this anymore. No time.

If you'd like, you can post questions in STM32 Forum to ask them to fix and/or make the new cores not breaking.

Good Luck,

**Comment by pxvga** [comment]
Thanks for your answer, I haven't been able to solve this problem yet, I'll try again. Tell me, are you planning to enable SD support in this example?

**Comment by pxvga** [comment]
Thanks for your answer, I haven't been able to solve this problem yet, I'll try again. Tell me, are you planning to enable SD support in this example?

**Comment by khoih-prog** [comment]
Sorry no. It's easy to do it yourself using any SD library supporting STM32.

**Comment by pxvga** [comment]
I'm sorry to take your time, but I couldn't get the -request->send(SD, "/index.html",... construction to work, although working with SD is fine; maybe I don't have enough experience, and I don't want to work through the buffer .
Thanks for the answer

**Comment by khoih-prog** [comment]
I can just only recommend you start from the simplest example [**AsyncWebServer_SendChunked**](https://github.com/khoih-prog/AsyncWebServer_STM32/tree/master/examples/AsyncWebServer_SendChunked), where you can send a very large data from local buffer.

Then moving on to experiment from **reading SD -> local buffer -> send chunks as in the example**

When you have better experience, modify / write the better code yourself.

**Comment by pxvga** [comment]
I have some experience with ESPAsyncWebServer +SPIFFS and wanted to get the same environment on STM32 (I need ETH). I imagine working through memory, but I wanted to direct the flow directly
Thank you for wasting time on me

**Comment by khoih-prog** [comment]
If so, why not using mature ESP2-based `WT32_ETH01`, with built-in LAN8720 and better support ?

**Comment by khoih-prog** [comment]
Check [**AsyncWebServer_WT32_ETH01**](https://github.com/khoih-prog/AsyncWebServer_WT32_ETH01) library if you're interested.

**Comment by pxvga** [comment]
after connecting LAN872 there are 4 pins left :(
In any case, thanks for your work.
